@VisualNovelApi_HostAddress = http://localhost:5235

### GET all

GET {{VisualNovelApi_HostAddress}}/api/novels
Content-Type: application/json

### GET single

GET {{VisualNovelApi_HostAddress}}/api/novels/282ec692-f2c1-492e-abf6-ac6322b41f9a
Content-Type: application/json

### CREATE

POST {{VisualNovelApi_HostAddress}}/api/novels
Content-Type: application/json

{
    "id": "64850efe-3659-47db-876f-ed0b46682b94",
    "title": "2023-05-10",
    "coverUrl": "hello"
}

# ### UPDATE

# PUT {{VisualNovelApi_HostAddress}}/api/novels
# Content-Type: application/json

# {
#     "title": "2023-05-10",
#     "coverUrl": 30,
#     "summary": "Warm"
# }

### DELETE

DELETE {{VisualNovelApi_HostAddress}}/api/novels/64850efe-3659-47db-876f-ed0b46682b94
Content-Type: application/json
