@VisualNovelApi_HostAddress = http://localhost:5235

GET {{VisualNovelApi_HostAddress}}/api/novels
Content-Type: application/json

###

GET {{VisualNovelApi_HostAddress}}/api/novels?id=1
Content-Type: application/json

{
    "title": "2023-05-10",
    "coverUrl": 30,
    "summary": "Warm"
}
